/**
 * Seed the features catalog.
 * Run: npx tsx scripts/seed-features.ts
 */
import "dotenv/config";
import { db } from "@/lib/db";
import { features } from "@/db/schema";

const FEATURES = [
  // ── EXTRACTION ──────────────────────────────────────────────────
  {
    id: "ai_tiered_fallback",
    name: "Fallback automático Flash → Pro",
    description: "Reintenta documentos con baja confianza usando Gemini Pro cuando Gemini Flash falla.",
    category: "extraction" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: true,
    defaultConfig: {
      soft_fallback_rate: 0.08,
      canary_rate: 0.00,
      sticky_secondary_enabled: true,
      allow_secondary_for_baldor: false,
      complex_line_count_threshold: 12,
      primary_max_retries: 3,
      secondary_max_retries: 1,
      retry_base_ms: 1500,
      retry_max_ms: 8000,
    },
    configSchema: [
      { key: "soft_fallback_rate", label: "Tasa reintento suave (0–1)", type: "number", min: 0, max: 1, description: "% de fallos suaves que se reenvían al modelo Pro" },
      { key: "canary_rate", label: "Tasa canary (0–1)", type: "number", min: 0, max: 0.5, description: "% de éxitos Flash también probados en Pro" },
      { key: "sticky_secondary_enabled", label: "Sticky secundario", type: "boolean", description: "Una vez que un doc usa Pro, sigue usándolo" },
      { key: "allow_secondary_for_baldor", label: "Permitir Pro para Baldor", type: "boolean", description: "Permite fallback a Pro en facturas Baldor" },
      { key: "complex_line_count_threshold", label: "Umbral de líneas complejas", type: "number", min: 3, max: 200, description: "Docs con más líneas van directo al modelo Pro" },
      { key: "primary_max_retries", label: "Reintentos modelo primario", type: "number", min: 0, max: 5 },
      { key: "secondary_max_retries", label: "Reintentos modelo secundario", type: "number", min: 0, max: 3 },
      { key: "retry_base_ms", label: "Delay base reintentos (ms)", type: "number", min: 250, max: 10000 },
      { key: "retry_max_ms", label: "Delay máximo reintentos (ms)", type: "number", min: 1000, max: 60000 },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 10,
  },
  {
    id: "ai_force_secondary",
    name: "Forzar modelo Pro en todos los documentos",
    description: "Envía todos los documentos directamente al modelo Pro. Mayor costo, máxima precisión.",
    category: "extraction" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 11,
  },
  {
    id: "ai_model_selection",
    name: "Selección de modelos AI",
    description: "Configura qué modelos Gemini se usan y el límite de caracteres por documento.",
    category: "extraction" as const,
    featureType: "config" as const,
    defaultEnabled: true,
    defaultConfig: { primary_model: "gemini-2.5-flash", secondary_model: "gemini-2.5-pro", max_chars: 65000 },
    configSchema: [
      { key: "primary_model", label: "Modelo primario", type: "select", options: ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-2.5-pro"] },
      { key: "secondary_model", label: "Modelo secundario (fallback)", type: "select", options: ["gemini-2.5-pro", "gemini-2.5-flash"] },
      { key: "max_chars", label: "Máx caracteres por documento", type: "number", min: 10000, max: 200000 },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 12,
  },
  {
    id: "ai_validation_thresholds",
    name: "Umbrales de validación de extracción",
    description: "Controla qué diferencia entre total extraído y suma de líneas se considera error.",
    category: "extraction" as const,
    featureType: "config" as const,
    defaultEnabled: true,
    defaultConfig: { hard_fail_abs_diff: 5.00, hard_fail_pct: 0.02, tolerance_abs: 0.50, tolerance_pct: 0.01 },
    configSchema: [
      { key: "hard_fail_abs_diff", label: "Diferencia absoluta para fallo duro ($)", type: "number", min: 0, max: 1000 },
      { key: "hard_fail_pct", label: "Diferencia porcentual fallo duro (0–1)", type: "number", min: 0, max: 1 },
      { key: "tolerance_abs", label: "Tolerancia absoluta ($)", type: "number", min: 0, max: 100 },
      { key: "tolerance_pct", label: "Tolerancia porcentual (0–1)", type: "number", min: 0, max: 0.5 },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 13,
  },
  // ── MAPPING ─────────────────────────────────────────────────────
  {
    id: "auto_mapping",
    name: "Auto-mapeo de ítems",
    description: "Aprende de mapeos confirmados y los aplica automáticamente.",
    category: "mapping" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: true,
    defaultConfig: { min_confirmations: 5, merge_similarity: 0.93, suggest_similarity: 0.84, vendor_suggest_similarity: 0.90 },
    configSchema: [
      { key: "min_confirmations", label: "Confirmaciones mínimas para auto-mapeo", type: "number", min: 1, max: 50 },
      { key: "merge_similarity", label: "Similitud para fusionar (0.6–1.0)", type: "number", min: 0.6, max: 1 },
      { key: "suggest_similarity", label: "Similitud para sugerir (0.5–1.0)", type: "number", min: 0.5, max: 1 },
      { key: "vendor_suggest_similarity", label: "Similitud cruzada proveedores (0.7–1.0)", type: "number", min: 0.7, max: 1 },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 20,
  },
  // ── WORKFLOW ────────────────────────────────────────────────────
  {
    id: "po_processing",
    name: "Comportamiento de procesamiento de POs",
    description: "Controla cómo se aplican las órdenes de compra al enviar a NetSuite.",
    category: "workflow" as const,
    featureType: "config" as const,
    defaultEnabled: true,
    defaultConfig: { apply_to_po_lines: true, set_unselected_po_lines_to_zero: false, allow_additional_lines: true },
    configSchema: [
      { key: "apply_to_po_lines", label: "Aplicar factura a líneas de PO", type: "boolean" },
      { key: "set_unselected_po_lines_to_zero", label: "Poner líneas no seleccionadas en cero", type: "boolean" },
      { key: "allow_additional_lines", label: "Permitir líneas adicionales", type: "boolean" },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 30,
  },
  {
    id: "netsuite_dry_run",
    name: "Modo prueba en NetSuite (Dry Run)",
    description: "Valida documentos contra NetSuite pero NO crea transacciones reales.",
    category: "workflow" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 31,
  },
  {
    id: "approval_workflow",
    name: "Flujo de aprobación",
    description: "Requiere aprobación de un Admin antes de enviar documentos a NetSuite.",
    category: "workflow" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: true,
    sortOrder: 32,
  },
  {
    id: "duplicate_detection",
    name: "Detección de facturas duplicadas",
    description: "Alerta cuando se procesa una factura con número y proveedor ya existente.",
    category: "workflow" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: true,
    sortOrder: 33,
  },
  {
    id: "bulk_upload",
    name: "Carga masiva de documentos",
    description: "Sube múltiples documentos a la vez y los procesa en cola.",
    category: "workflow" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: true,
    sortOrder: 34,
  },
  {
    id: "exception_queue",
    name: "Cola de excepciones",
    description: "Documentos fallidos van a una cola con diagnóstico y opción de reintento.",
    category: "workflow" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 35,
  },
  {
    id: "custom_netsuite_forms",
    name: "Formularios personalizados en NetSuite",
    description: "Especifica Custom Form IDs para facturas y POs en NetSuite.",
    category: "workflow" as const,
    featureType: "config" as const,
    defaultEnabled: false,
    defaultConfig: { po_customform_id: "", invoice_customform_id: "" },
    configSchema: [
      { key: "po_customform_id", label: "Custom Form ID para Purchase Orders", type: "string" },
      { key: "invoice_customform_id", label: "Custom Form ID para Facturas", type: "string" },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 36,
  },
  // ── SYNC ────────────────────────────────────────────────────────
  {
    id: "auto_sync",
    name: "Sincronización automática de catálogos",
    description: "Sincroniza ítems, proveedores y ubicaciones desde NetSuite automáticamente.",
    category: "sync" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: false,
    defaultConfig: { interval_hours: 24, check_every_minutes: 5, start_delay_seconds: 20 },
    configSchema: [
      { key: "interval_hours", label: "Intervalo entre sincronizaciones (horas)", type: "number", min: 1, max: 168 },
      { key: "check_every_minutes", label: "Frecuencia de verificación (min)", type: "number", min: 1, max: 60 },
      { key: "start_delay_seconds", label: "Delay inicial al arrancar (seg)", type: "number", min: 0, max: 300 },
    ],
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 40,
  },
  {
    id: "sync_advanced",
    name: "Configuración avanzada de sincronización",
    description: "Tamaño de página, límites por subsidiaria y timeout de peticiones a NetSuite.",
    category: "sync" as const,
    featureType: "config" as const,
    defaultEnabled: true,
    defaultConfig: { page_size: 500, mx_max_subsidiaries_per_run: 0, mx_service_category_id: 6, request_timeout_ms: 45000 },
    configSchema: [
      { key: "page_size", label: "Tamaño de página de sync", type: "number", min: 50, max: 2000 },
      { key: "mx_max_subsidiaries_per_run", label: "Máx subsidiarias MX por corrida (0=todas)", type: "number", min: 0, max: 100 },
      { key: "mx_service_category_id", label: "ID categoría de servicios MX", type: "number", min: 1 },
      { key: "request_timeout_ms", label: "Timeout peticiones NetSuite (ms)", type: "number", min: 5000, max: 120000 },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 41,
  },
  // ── INTEGRATION ─────────────────────────────────────────────────
  {
    id: "webhook_system",
    name: "Webhooks",
    description: "Notificaciones HTTP a sistemas externos en eventos de documentos y syncs.",
    category: "integration" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 50,
  },
  {
    id: "api_keys",
    name: "API Keys",
    description: "Acceso programático para integrar DocuIA con otros sistemas.",
    category: "integration" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 51,
  },
  {
    id: "scheduled_reports",
    name: "Reportes automáticos por email",
    description: "Resumen semanal/mensual con documentos, proveedores top y errores.",
    category: "integration" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 52,
  },
  // ── ANALYTICS ───────────────────────────────────────────────────
  {
    id: "advanced_analytics",
    name: "Estadísticas avanzadas",
    description: "Dashboards de tendencias, análisis por proveedor y métricas de AI.",
    category: "analytics" as const,
    featureType: "boolean" as const,
    defaultEnabled: true,
    defaultConfig: null,
    configSchema: null,
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 60,
  },
  {
    id: "data_export",
    name: "Exportación de datos",
    description: "Exporta historial de documentos a Excel o CSV.",
    category: "analytics" as const,
    featureType: "boolean" as const,
    defaultEnabled: true,
    defaultConfig: null,
    configSchema: null,
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 61,
  },
  {
    id: "data_retention",
    name: "Retención de datos",
    description: "Define por cuántos días se conservan documentos, logs e historial.",
    category: "analytics" as const,
    featureType: "config" as const,
    defaultEnabled: true,
    defaultConfig: { documents_retention_days: -1, logs_retention_days: 90, history_retention_days: -1 },
    configSchema: [
      { key: "documents_retention_days", label: "Retención de documentos (días, -1=siempre)", type: "number", min: -1, max: 3650 },
      { key: "logs_retention_days", label: "Retención de logs (días)", type: "number", min: 7, max: 730 },
      { key: "history_retention_days", label: "Retención de historial (días, -1=siempre)", type: "number", min: -1, max: 3650 },
    ],
    planRequired: "starter" as const,
    isBeta: false,
    sortOrder: 62,
  },
  // ── STORAGE ─────────────────────────────────────────────────────
  {
    id: "document_storage",
    name: "Almacenamiento de documentos originales",
    description: "Guarda archivos originales (PDF, Excel, XML) en MinIO para reprocesamiento.",
    category: "storage" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: false,
    defaultConfig: { retention_days: -1 },
    configSchema: [
      { key: "retention_days", label: "Días de retención (-1=siempre)", type: "number", min: -1, max: 3650 },
    ],
    planRequired: "growth" as const,
    isBeta: false,
    sortOrder: 70,
  },
  // ── SECURITY ────────────────────────────────────────────────────
  {
    id: "ip_allowlist",
    name: "Lista blanca de IPs",
    description: "Restringe el acceso a IPs específicas o rangos CIDR.",
    category: "security" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: false,
    defaultConfig: { allowed_ips: [] },
    configSchema: [
      { key: "allowed_ips", label: "IPs permitidas (separadas por coma)", type: "string", description: "Ej: 192.168.1.0/24, 10.0.0.1" },
    ],
    planRequired: "enterprise" as const,
    isBeta: false,
    sortOrder: 80,
  },
  {
    id: "sso_saml",
    name: "SSO / SAML",
    description: "Autenticación empresarial con Okta, Azure AD, Google Workspace.",
    category: "security" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: false,
    defaultConfig: { saml_entry_point: "", saml_issuer: "", saml_cert: "" },
    configSchema: [
      { key: "saml_entry_point", label: "Entry Point URL del IdP", type: "string" },
      { key: "saml_issuer", label: "Issuer / Entity ID", type: "string" },
      { key: "saml_cert", label: "Certificado público (PEM)", type: "string" },
    ],
    planRequired: "enterprise" as const,
    isBeta: false,
    sortOrder: 81,
  },
  {
    id: "tenant_audit_log",
    name: "Log de auditoría de usuarios",
    description: "Registra todas las acciones de usuarios: login, documentos, cambios de config.",
    category: "security" as const,
    featureType: "boolean" as const,
    defaultEnabled: false,
    defaultConfig: null,
    configSchema: null,
    planRequired: "enterprise" as const,
    isBeta: false,
    sortOrder: 82,
  },
  // ── EXPENSES ────────────────────────────────────────────────────
  {
    id: "expense_management",
    name: "Módulo de Gastos (Expense AI)",
    description: "Habilita el flujo completo de informes de gastos: captura móvil, OCR, validaciones fiscales, aprobación y creación automática en NetSuite.",
    category: "expenses" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: false,
    defaultConfig: {
      country_code: "CO",
      auto_create_vendor: true,
      duplicate_check_enabled: true,
      spending_caps_enabled: true,
      documento_equivalente_form_id: "",
    },
    configSchema: [
      { key: "country_code", label: "País principal (CO, MX, CL...)", type: "string" },
      { key: "auto_create_vendor", label: "Crear proveedor automáticamente si no existe en NS", type: "boolean" },
      { key: "duplicate_check_enabled", label: "Detectar gastos duplicados", type: "boolean" },
      { key: "spending_caps_enabled", label: "Validar topes de gasto por categoría", type: "boolean" },
      { key: "documento_equivalente_form_id", label: "Custom Form ID de Documento Equivalente en NS", type: "string" },
    ],
    planRequired: "enterprise" as const,
    isBeta: true,
    sortOrder: 100,
  },
  {
    id: "expense_approval",
    name: "Aprobación de informes de gastos",
    description: "Requiere aprobación de un manager o admin antes de sincronizar el informe a NetSuite.",
    category: "expenses" as const,
    featureType: "boolean" as const,
    defaultEnabled: true,
    defaultConfig: null,
    configSchema: null,
    planRequired: "enterprise" as const,
    isBeta: false,
    sortOrder: 101,
  },
  {
    id: "expense_categories_sync",
    name: "Sincronización automática de catálogos de gastos",
    description: "Sincroniza categorías, departamentos, clases y empleados desde NetSuite automáticamente.",
    category: "expenses" as const,
    featureType: "boolean" as const,
    defaultEnabled: true,
    defaultConfig: null,
    configSchema: null,
    planRequired: "enterprise" as const,
    isBeta: false,
    sortOrder: 102,
  },
  // ── ENTERPRISE ──────────────────────────────────────────────────
  {
    id: "white_label",
    name: "White Label / Marca personalizada",
    description: "Personaliza logo, colores y oculta referencias a DocuIA.",
    category: "enterprise" as const,
    featureType: "boolean_config" as const,
    defaultEnabled: false,
    defaultConfig: { company_name: "", logo_url: "", primary_color: "#1E3A8A", hide_branding: false },
    configSchema: [
      { key: "company_name", label: "Nombre de la empresa", type: "string" },
      { key: "logo_url", label: "URL del logo", type: "string" },
      { key: "primary_color", label: "Color primario (hex)", type: "string" },
      { key: "hide_branding", label: "Ocultar branding de DocuIA", type: "boolean" },
    ],
    planRequired: "enterprise" as const,
    isBeta: false,
    sortOrder: 90,
  },
] as const;

async function main() {
  console.log("Seeding features catalog...");

  for (const f of FEATURES) {
    await db
      .insert(features)
      .values(f)
      .onConflictDoUpdate({
        target: features.id,
        set: {
          name: f.name,
          description: f.description,
          defaultEnabled: f.defaultEnabled,
          defaultConfig: f.defaultConfig,
          configSchema: f.configSchema,
          planRequired: f.planRequired,
          isBeta: f.isBeta,
          sortOrder: f.sortOrder,
        },
      });
    console.log(`  ✓ ${f.id}`);
  }

  console.log(`\nDone! ${FEATURES.length} features seeded.`);
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
